### PR TITLE
omegadex: generate HTML files from .txt

### PR DESCRIPTION
**Pull request by straightCrimpin**
This commit adds logical extensions to create HTML files from the existing .txt files. This comes in the form of a python script which parses all .txt files from Data directory and generates HTML. The HTML files are then served rather than the .txt files. Summary of changes below.

- Add build directory with the following:
  - create_html.py : main script containing logic to create HTML templates, parse text content, and create HTML files.
  - clean_html.py : Removes generated content
  - config: directory containing .json files which contain arguments for RuleSet Classes
  - lib\Rules: rules.py : Library containin RuleSet classes which are classes that parse text files differently depending on the type of text file expected.

Other Changes

  - Add background image Hexagons.png
  - Update styles.css to include Variant class colors and other commonly used styles.
  - Minor changes to various text files to improve text parsing.
  - update content.php to serve html files rather than .txt files
  - update navigation_sub.php to sort Changelog by date, decending
  - update .github\workflows to install python 3.12 on workflow server install requirements.txt if it exists, and run create_html.py. In conjnction with the other changes this should dynamically create the html files and serve them up with commit changes.

### CODE REVIEW

**Comment by Eidigii** [comment]
Looking good.
The only problem I see, is with line breaks getting eaten on some occasions in the html files,
e.g. take a look at the "Paragons" page.

**Comment by straightCrimpin** [comment]
> Looking good. The only problem I see, is with line breaks getting eaten on some occasions in the html files, e.g. take a look at the "Paragons" page.

Ah, good call. I forgot to push the change I had made to the paragons txt file and accidentally overwrote it. Should be fixed now.

**Comment by Eidigii** [comment]
It also affects any long texts with paragraphs (Progression Guides). Maybe change the python builder to create html paragraph elements?

**Comment by straightCrimpin** [comment]
> It also affects any long texts with paragraphs (Progression Guides). Maybe change the python builder to create html paragraph elements?

I tried paragraph elements, and they don't look that good or work well with the rest of the logic. I probably can make the whole thing cleaner but it might take some time. I will submit a quick-and-dirty fix for now to make sure paragraphs are more clear (though it does have the unintended side-effect of creating too many line breaks on headers), and when I get some more time I will work on getting the whole thing cleaner.

**Comment by straightCrimpin** [comment]
Alright, I think that's fixed up a whole lot better. Let me know if you want any more changes or if you're good with this as is.

**Pull request merged**
